spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootonttomany?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      #no hibernate sequence table
      use-new-id-generator-mappings: false
      ddl-auto: create